### PR TITLE
Fix drag and drop tasks

### PR DESCRIPTION
**Pull request by fabiiomiiguel**
Hello again :)

With the latest npm build maybe because of one merge, some code as gantt.api.tasks.raise.change, I changed to api.tasks.raise.change only.

The function getDateByPosition was missing the moment import, because this project uses typescript and rollup, I found a workaround to import that.
`
 import * as moment_ from 'moment';
 const moment = moment_
`
[Source](https://github.com/jvandemo/generator-angular2-library/issues/221#issuecomment-516445049)

I tested and that changes fixes the errors, but see by yourself if it is a good resolution. Thank you.

### CODE REVIEW

**Comment by ANovokmet** [comment]
Thanks, I will check it out. I did not want momentjs to be included in the build, it makes sense to include it but sometimes the client will already import it.

**Comment by fabiiomiiguel** [comment]
Can you at least merge src/entities/Task.svelte fix?

**Comment by ANovokmet** [comment]
I pushed the fix for src/entities/Task.svelte (https://github.com/ANovokmet/svelte-gantt/commit/bdefddebf194d761dce2ede4ba18cf8f440e2785), and published to npm. I will review this pull request as soon as I'm able to.

**Comment by fabiiomiiguel** [comment]
Thanks, you are the best!

**Comment by fabiiomiiguel** [comment]
If you are using Vue.js 2 and you want to use this package. You will need to do one of the next two things:

First one is to import the moment and set that on your main.js:
```
import moment from 'moment';
window.moment = moment;
```
Second one, if you want only to import moment in one component:
```
<script>
import moment from 'moment';

export default {

  ...

  created() {
    window.moment = moment;
  },

  ...

  destroyed() {
    delete window.moment;
  },

  ...

};
</script>

**Comment by ANovokmet** [comment]
Thanks for this, I checked the ES module build and can now see what is the issue. Hopefully, we can break the need to add moment to window in ES builds.

**Comment by ANovokmet** [comment]
@fabiiomiiguel how are you importing svelte-gantt into your Vue app? 

If you are using es6 import `import { SvelteGantt } from 'svelte-gantt';` you should be able to use it without adding moment to the window. At least now you should, since some parts of svelte-gantt were missing the import :)

**Comment by fabiiomiiguel** [comment]
I'm importing in that exact way.

```
import {
  SvelteGantt,
  SvelteGanttTable,
  SvelteGanttDependencies,
} from 'svelte-gantt';
```

But yes now it's fixed! Thanks :)

**Pull request closed without merging**
