### PR TITLE
Fixes multiple selection and more

### PR DESCRIPTION
**Pull request by BlueFoxPrime**
Main changes/ fixes:

   - types for getContext
   - dragging of multiple tasks in a single event loop (fix "overrezizing case" and accurracy on "offset" tasks) 
   #129
   - including performance optimisations in task.svelte and store.ts (update all selected at once + use for loops)
   - removed not needed logic/ reactive statements from Gantt.svelte regarding columns
   - absolute positioning on body columns to keep borders in sync with header column borders
   - change body column background color to use durations (simplification and flexibility to highlight different units or intervalls)
   - removing unecessary reactive statements and other small improvements ...

### CODE REVIEW

**Review by V-Py — APPROVED** [review]
Incredible job !! I'm merging after reviewing it as best as I could, and testing it with the "old" demo.
Didn't notice any problems. However there is problems in the SvelteKit demo which isn't working properly, but was prior to your PR, so I'll give it a look after integrating this.

**Comment by BlueFoxPrime** [comment]
Thank you. I will try to keep PRs smaller in the future so they are easier to merge and check. I am looking for further cleanups and improvements. The next feature I will add is an option to display horizontal lines between rows, or last child and next parent row in tree view.

**Comment by BlueFoxPrime** [comment]
@V-Py Did you make any progress with the sveltekit version? I was thinking if it wasnt better to transform the whole app to sveltekit...

**Comment by V-Py** [comment]
@BlueFoxPrime I'm kinda buried under work recently ... So didn't have time to take care of anything for the svelte gantt repo sadly ..! 😞 

@ANovokmet if you see this, wouldn't be nice to have @BlueFoxPrime as a repo maintainer ? He's way more productive than me atm, have good ideas, and producing really good quality code ?

**Comment by BlueFoxPrime** [comment]
@V-Py @ANovokmet I am also pretty busy too but once in a while I find some time to tinker around. Its probably not enugh to maintain this thing alone... If I can find the time though I will rebuild the whole libary as a plugin/ extention:
https://svelte.dev/repl/ff8d56147d2b44428e0d39f576dfb82c?version=3.55.1

The grid layout brings a lot of advantages and that existing table libary has a lot of nice features. The handling of rows and y position can completely be abandoned... I am currently thinking about whether it would make sense to keep the taskStore (and combine tasks and rows with a derived store) or include the tasks in the rows in input data (limited accessability).

**Comment by Edward-Ta** [comment]
> @V-Py Did you make any progress with the sveltekit version? I was thinking if it wasnt better to transform the whole app to sveltekit...

If the whole app was to be transformed into SvelteKit, would this cause a problem for people who dont use SvelteKit and only use svelte-gantt in a regular svelte project, that is compiled to serve in our own backends?

**Pull request merged**
