### PR TITLE
Fixing incorrect layout generation for columns/header

### PR DESCRIPTION
**Pull request by V-Py**

### CODE REVIEW

**Comment by Vitalik549** [comment]
Hey, thanks for this PR! Could you please advise when the next version release of [svelte-gantt](https://github.com/ANovokmet/svelte-gantt) expected with these changes included?

**Comment by V-Py** [comment]
Hey, I think the next release will be tomorrow or tuesday!

**Comment by V-Py** [comment]
@Vitalik549 sorry for the delay, I'm waiting some corrections linked to #129 before releasing

**Comment by BlueFoxPrime** [comment]
@V-Py Sorry for the delay but it wasnt possible for me to post my fixes. Will do so this weekend!

**Pull request merged**
